
---
output:
  html_document:
      keep_md: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message=FALSE, comment="#>", fig.width=8, fig.height=8, fig.align="center")
```

### Requirements

- Docker version >= 18
- Git version >= 2.21.0

### Steps to run sc2-spike-seq container

#### (1) Clone this respitory

```
git clone https://github.com/nbx0/SC2-spike-seq/tree/container_init
``` 

#### (2) CD to `sc2-spike-seq` folder 

#### (3) Check out `container_init` branch

```
git checkout container_init 
```

#### (4) Pull down irma and dais-ribosome images

- From a docker registry

&emsp; **BR**: `docker pull public.ecr.aws/n3z8t4o2/irma:1.0.2p3` <br>
&emsp; **Dias-Ribosome**: `docker pull public.ecr.aws/n3z8t4o2/dais-ribosome:1.2.1`

- From a tarball 

&emsp; **IRMA**:	`docker load -i containers/irma:1.0.2p3.tar` <br>
&emsp; **Dais-Ribosome**: `docker load -i containers/dais-ribosome:1.2.1.tar`

#### (5) Run **irma** and **dais-ribosome** containers

&emsp; **IRMA**: `docker run -v /path/to/data:/data --name irma:1.0.2p3 -t -d public.ecr.aws/n3z8t4o2/irma:1.0.2p3` <br>
&emsp; **Dais-Ribosome**: `docker run -v /path/to/data:/data --name dais-ribosome:1.2.1 -t -d public.ecr.aws/n3z8t4o2/dais-ribosome:1.2.1`

#### (6) Build **sc2-spike-seq** image and container

__NOTE:__ In the `SC2-seq-spike` directory, there is a `Dockerfile` that contains a list of instructions and steps of how to build and run the `sc2-spike-seq` workflow.

**A. Build the development version**

```
docker build -t sc2-spike-seq-dev:v1.0.0 --build-arg BUILD_STAGE=dev .
```

**-t**: add a tag to an image such as the version of the application, e.g. *sc2-spike-seq-dev:v1.0.0* or *sc2-spike-seq-dev:latest* <br>
**`--`build-arg**: set the build stage for the docker image. In this case, we want to build the **development** stage. <br>

_The image took approximately < 10 mins to build_

After the build is completed, you can check if the image is built successfully

```
docker images

REPOSITORY             TAG        IMAGE ID        CREATED        SIZE
sc2-spike-seq-dev      v1.0.0     2c22887402d3    2 hours ago    1.49GB
```

To run the `sc2-spike-seq-dev` container

```    
docker run -v /path/to/data:/data -v /path/to/sc2-spike-seq:/sc2-spike-seq -v /var/run/docker.sock:/var/run/docker.sock --name sc2-spike-seq-dev-1.0.0 -t -d sc2-spike-seq-dev:v1.0.0 
```

**NOTE:** <br>
- Change __/path/to/data__ to your local directory where it contains all data files needed to feed into the `sc2-spike-seq` workflow. This directory is mounted to `/data` directory inside the container. <br>
- Change __/path/to/sc2-spike-seq__ to your local `sc2-spike-seq` directory. This directory must contain all of the code base needed to build the `sc2-spike-seq` workflow. <br>
- **/var/run/docker.sock:/var/run/docker.sock** is used to connect the host's docker.socket to container's docker.socket where you can run a container inside of another container. <br>

**-d**: run the container in detached mode <br>
**-v**: mount code base and data files from host directory to container directory **[host_div]:[container_dir]**. By exposing the host directory to docker container, docker will be able to access data files within that mounted directory and use it to fire up the `sc2-spike-seq` workflow.  <br>
**-p**: map the host port to the container port and then all the requests that are made to the host port will be redirected to the Docker container **[host_port]:[container_port]** <br>
**`--`name**: give an identity to the container <br>

For more information about the Docker syntax, see [Docker run reference](https://docs.docker.com/engine/reference/run/)

To check if the container is built successfully

```
docker container ps


CONTAINER ID   IMAGE                        COMMAND                       CREATED        STATUS        PORTS      NAMES
b37b6b19c4e8   sc2-spike-seq-dev:v1.0.0    "/bin/bash -c snake-kickoff"   5 hours ago    Up 5 hours               sc2-spike-seq-dev-1.0.0
```

**B. Build the production version**

```
docker build -t sc2-spike-seq-prod:v1.0.0 .
```

**-t**: add a tag to an image such as the version of the application, e.g. *sc2-spike-seq-prod:v1.0.0* or *sc2-spike-seq-prod:latest* <br>

_The image took approximately < 10 mins to build_

After the build is completed, you can check if the image is built successfully

```
docker images

REPOSITORY             TAG        IMAGE ID        CREATED        SIZE
sc2-spike-seq-prod     v1.0.0     2c22887402d3    2 hours ago    1.49GB
```

To run the `sc2-spike-seq-prod` container

```    
docker run -v /path/to/data:/data -v /var/run/docker.sock:/var/run/docker.sock --name sc2-spike-seq-prod-1.0.0 -t -d sc2-spike-seq-prod:v1.0.0 
```

**NOTE:** <br>
- Change __/path/to/data__ to your local directory where it contains all data files needed to feed into the `sc2-spike-seq` workflow. This directory is mounted to `/data` directory inside the container. <br>
- **/var/run/docker.sock:/var/run/docker.sock** is used to connect the host's docker.socket to container's docker.socket where you can run a container inside of another container. <br>

**-d**: run the container in detached mode <br>
**-v**: mount code base and data files from host directory to container directory **[host_div]:[container_dir]**. By exposing the host directory to docker container, docker will be able to access data files within that mounted directory and use it to fire up the `sc2-spike-seq` workflow.  <br>
**-p**: map the host port to the container port and then all the requests that are made to the host port will be redirected to the Docker container **[host_port]:[container_port]** <br>
**`--`name**: give an identity to the container <br>

For more information about the Docker syntax, see [Docker run reference]()

To check if the container is built successfully

```
docker container ps


CONTAINER ID   IMAGE                        COMMAND                           CREATED        STATUS        PORTS      NAMES
475741fd9bc7   sc2-spike-seq-prod:v1.0.0    "/bin/bash -c snake-kickoff"      5 hours ago    Up 5 hours               sc2-spike-seq-prod-1.0.0
```

#### (7) Execute commands in **sc2-spike-seq** container

```
docker exec -w /data -it sc2-spike-seq-prod-1.0.0 bash snake-kickoff <path to samplesheet.csv> <path to instrument run> <Nanopore run name>
```

#### (8) Execute commands in **irma-1.0.2p3** container

```
docker exec -w /data irma-1.0.2p3 

USAGE:
(PAIRED-END):   IRMA <MODULE|MODULE-CONFIG> <R1.fastq.gz|R1.fastq> <R2.fastq.gz|R2.fastq> [path/to/]<sample_name>
(SINGLE-END):   IRMA <MODULE|MODULE-CONFIG> <fastq|fastq.gz> [path/to/]<sample_name>
```

<br>

Any questions or issues? Please report them on our [github issues](https://github.com/nbx0/SC2-spike-seq/issues)

<br>


