#!/bin/bash

hUser=$(whoami)
password_file="~/hadoop/.impala"

function readlinkf() {
	if [ "$(uname -s)" == "Darwin" ];then
		perl -MCwd -e 'print Cwd::abs_path shift' "$1"
	else
		readlink -f "$1"
	fi
}

if [ "$HADOOP_DB" != "" ];then
	hDB=$HADOOP_DB
else
	hDB="dais"
fi

if [ "$HADOOP_IMPALA_PASSWORD_FILE" != "" ];then
	password_file=$HADOOP_IMPALA_PASSWORD_FILE
else
	password_file="~/hadoop/.beeline"
fi

if [ "$HADOOP_HOST" != "" ];then
	hHost=$HADOOP_HOST
else
	hHost="flu-hadoop-05.biotech.cdc.gov"
fi

hLogin=$hUser@$hHost
query='show tables'

if [ "$#" -eq "1" ];then
	query=$1
elif [ "$#" -eq "2" ];then
	query=$1
	hDB=$2
elif [ "$#" -eq "3" ];then
	query=$1
	hDB=$2
	password_file=$3
else
	echo -e "Usage:\n\t$0 <query> [database] [password_file_path_on_HADOOP_HOST]"
	exit 0
fi

CMD="impala-shell -u $hUser -i localhost:21000 -d $hDB --quiet -B"
if [ -s "$query" ] ; then
	# Query is in a local file see, if it is on the remote host
	filename=$(readlinkf $query)
	if ssh $hLogin stat "$filename" > /dev/null 2>&1 ;then
		CMD+=" -f '$filename'" 
	else
		query=$(cat $query|tr \' \")
		CMD+=" -q '$query'"
	fi
else
	# Query is not a local file but could be a remote file
	if ssh $hLogin stat "$query" > /dev/null 2>&1 ;then
		filename=$query
		CMD+=" -f '$filename'" 
	else
		query=$(tr \' \" <<< "$query")
		CMD+=" -q '$query'"
	fi
fi

exec 3>&1
OUTPUT=$(ssh $hLogin "$CMD" 2>&1 1>&3)
STATUS=$?
exec 3>&-

if [ "$STATUS" -ne "0" ];then
	echo "ERROR ($STATUS): $0" 1>&2
	echo "TRIED CMD: ssh $hLogin $CMD" 1>&2
	echo "-----------START-LOG---------------" 1>&2
	echo "$OUTPUT"|tail -n +45 1>&2
	echo "-----------END-LOG-----------------" 1>&2
	exit $STATUS
fi
