#!/bin/bash

hUser=$(whoami)

if [ "$HADOOP_HOST" != "" ];then
	hHost=$HADOOP_HOST
else
	hHost=flu-hadoop-05.biotech.cdc.gov
fi
hLogin=$hUser@$hHost

if [ "$HADOOP_IS_LOCAL" != "" ];then
	hLocal=$HADOOP_IS_LOCAL
else
	hLocal=0
fi

if [ "$#" -eq "1" ];then
	lFile=$1
	hDir=/user/$hUser
	hFile=$hDir/$(basename $lFile)
elif [ "$#" -eq "2" ];then
	lFile=$1
	if [ "${2: -1}" == "/" ];then
		hDir="$2"
		hFile="${hDir}$(basename $lFile)"
	else 
		hDir=$(dirname $2)
		hFile=$2
	fi
else
	echo -e "Usage:\n\t$0 <localfile> [/hdfs/path/dir/|/hdfs/path/file]"
	exit 0
fi

if [ ! -p "$lFile" ] && [ ! -r "$lFile" -o ! -s "$lFile" ];then
	echo -e "Invalid file: $lFile"
	exit 1
fi	

# Dual replication!
cdpFile=$(basename "$hFile")
cdpTable=$(basename $(dirname "$hFile"))
cdpHost="svc_dvd_clarity@cdp-client-01.biotech.cdc.gov"
cdpCache=/groups/NCIRD/DVD/data/snakemake-cache
scp "$lFile" "$cdpHost:$cdpCache/$cdpTable/$cdpFile" >/dev/null 2>&1 \
    && ssh "$cdpHost" "touch $cdpCache/$cdpTable/${cdpFile}.NEW" >/dev/null 2>&1 \
    || echo "SCP to CDP failed!" 1>&2

# Business as Usual
if [ "$hLocal" -eq "1" ];then
	ssh $hLogin "hdfs dfs -put -f $lFile $hFile" >/dev/null 2>&1
else
	OUTPUT=$(cat $lFile | ssh $hLogin "hdfs dfs -put -f - $hFile" 2>&1)
	STATUS=$?
	if [ "$STATUS" -ne "0" ];then
		echo "ERROR ($STATUS): $0" 1>&2
		echo "TRIED CMD: cat $lFile | ssh $hLogin \"hdfs dfs -put -f - $hFile\"" 1>&2
		echo "-----------START-LOG---------------" 1>&2
		echo "$OUTPUT"|tail -n +45 1>&2
		echo "-----------END-LOG-----------------" 1>&2
		exit $STATUS
	fi
fi
